var konspekt = [
    {"value":"61","kategorie":"14","label":"Lékařství","cislo_skupiny":""},
    {"value":"0/9-053.2","kategorie":"","label":"Literatura pro děti a mládež (naučná)","cislo_skupiny":"26"},
    {"value":"00","kategorie":"","label":"Věda. Všeobecnosti. Základy vědy a kultury. Vědecká práce","cislo_skupiny":"12"},
    {"value":"003","kategorie":"","label":"Systémy psaní a písma. Sémiotika (obecně)","cislo_skupiny":"11"},
    {"value":"003.05","kategorie":"","label":"Psaní a stenografie","cislo_skupiny":"4"},
    {"value":"004","kategorie":"","label":"Počítačová věda. Výpočetní technika. Informační technologie","cislo_skupiny":"23"},
    {"value":"004.2","kategorie":"","label":"Počítačová architektura","cislo_skupiny":"23"},
    {"value":"004.3","kategorie":"","label":"Počítače. Hardware","cislo_skupiny":"23"},
    {"value":"004.4/.6","kategorie":"","label":"Programování. Software","cislo_skupiny":"23"},
    {"value":"004.7","kategorie":"","label":"Počítačové sítě","cislo_skupiny":"23"},
    {"value":"004.8","kategorie":"","label":"Umělá inteligence","cislo_skupiny":"23"},
    {"value":"004.9","kategorie":"","label":"Speciální počítačové metody. Počítačová grafika","cislo_skupiny":"23"},
    {"value":"005","kategorie":"","label":"Management. Řízení","cislo_skupiny":"4"},
    {"value":"005.91/.92","kategorie":"","label":"Vedení úřadu (kanceláře). Spisová služba","cislo_skupiny":"4"},
    {"value":"005.91:82-6","kategorie":"","label":"Úřední korespondence","cislo_skupiny":"4"},
    {"value":"006","kategorie":"","label":"Metrologie. Standardizace","cislo_skupiny":"6"},
    {"value":"006.95","kategorie":"","label":"Chronologie","cislo_skupiny":"6"},
    {"value":"007","kategorie":"","label":"Teorie systémů. Automatické systémy. Informační systémy. Kybernetika","cislo_skupiny":"23"},
    {"value":"01","kategorie":"","label":"Bibliografie. Katalogy","cislo_skupiny":"12"},
    {"value":"02","kategorie":"","label":"Knihovnictví. Informatika","cislo_skupiny":"12"},
    {"value":"021","kategorie":"","label":"Funkce, význam a využívání knihoven","cislo_skupiny":"12"},
    {"value":"022","kategorie":"","label":"Budovy, areály a zařízení knihoven","cislo_skupiny":"12"},
    {"value":"023","kategorie":"","label":"Řízení knihoven","cislo_skupiny":"12"},
    {"value":"024","kategorie":"","label":"Služby knihoven","cislo_skupiny":"12"},
    {"value":"025","kategorie":"","label":"Organizace knihoven a knihovních fondů","cislo_skupiny":"12"},
    {"value":"025.3/.4","kategorie":"","label":"Katalogizace. Selekční jazyky","cislo_skupiny":"12"},
    {"value":"026","kategorie":"","label":"Odborné/speciální knihovny","cislo_skupiny":"12"},
    {"value":"026/027","kategorie":"","label":"Knihovny","cislo_skupiny":"12"},
    {"value":"027","kategorie":"","label":"Univerzální knihovny. Veřejné knihovny. Soukromé knihovny","cislo_skupiny":"12"},
    {"value":"028","kategorie":"","label":"Čtení. Četba","cislo_skupiny":"12"},
    {"value":"030","kategorie":"","label":"Všeobecná příručková díla","cislo_skupiny":"12"},
    {"value":"050","kategorie":"","label":"Seriálové publikace. Periodika","cislo_skupiny":"12"},
    {"value":"06","kategorie":"","label":"Organizace všeobecné povahy","cislo_skupiny":"12"},
    {"value":"061.2","kategorie":"","label":"Nevládní organizace a kooperace","cislo_skupiny":"18"},
    {"value":"069","kategorie":"","label":"Muzea. Muzeologie. Muzejnictví. Výstavy","cislo_skupiny":"12"},
    {"value":"070","kategorie":"","label":"Noviny. Tisk. Žurnalistika","cislo_skupiny":"12"},
    {"value":"08","kategorie":"","label":"Souborná díla","cislo_skupiny":"12"},
    {"value":"09","kategorie":"","label":"Rukopisy, prvotisky, staré tisky. Vzácná a pozoruhodná díla","cislo_skupiny":"12"},
    {"value":"093","kategorie":"","label":"Prvotisky","cislo_skupiny":"12"},
    {"value":"094","kategorie":"","label":"Staré tisky","cislo_skupiny":"12"},
    {"value":"094.5","kategorie":"","label":"Tisky (19. století)","cislo_skupiny":"12"},
    {"value":"095/096","kategorie":"","label":"Vzácná díla","cislo_skupiny":"12"},
    {"value":"101","kategorie":"","label":"Filozofie","cislo_skupiny":"5"},
    {"value":"11","kategorie":"","label":"Metafyzika","cislo_skupiny":"5"},
    {"value":"122/129","kategorie":"","label":"Speciální metafyzika","cislo_skupiny":"5"},
    {"value":"13","kategorie":"","label":"Filozofie ducha","cislo_skupiny":"5"},
    {"value":"133","kategorie":"","label":"Ezoterismus. Okultismus","cislo_skupiny":"17"},
    {"value":"14","kategorie":"","label":"Filozofické systémy a hlediska","cislo_skupiny":"5"},
    {"value":"14(100)\"04/14\"","kategorie":"","label":"Středověká filozofie","cislo_skupiny":"5"},
    {"value":"14(100-11)","kategorie":"","label":"Orientální filozofie","cislo_skupiny":"5"},
    {"value":"14(100-15)\"15/20\"","kategorie":"","label":"Moderní západní filozofie","cislo_skupiny":"5"},
    {"value":"14(3)","kategorie":"","label":"Antická, starověká filozofie","cislo_skupiny":"5"},
    {"value":"159.9","kategorie":"","label":"Psychologie","cislo_skupiny":"17"},
    {"value":"159.92","kategorie":"","label":"Vývojová psychologie. Individuální psychologie","cislo_skupiny":"17"},
    {"value":"159.929","kategorie":"","label":"Srovnávací psychologie","cislo_skupiny":"17"},
    {"value":"159.93/.94","kategorie":"","label":"Senzorické a motorické funkce. Emoce. Vůle","cislo_skupiny":"17"},
    {"value":"159.95","kategorie":"","label":"Vyšší duševní procesy","cislo_skupiny":"17"},
    {"value":"159.96","kategorie":"","label":"Zvláštní duševní stavy a procesy. Hlubinná psychologie","cislo_skupiny":"17"},
    {"value":"159.97","kategorie":"","label":"Psychopatologie","cislo_skupiny":"17"},
    {"value":"159.98","kategorie":"","label":"Aplikovaná psychologie","cislo_skupiny":"17"},
    {"value":"16","kategorie":"","label":"Logika","cislo_skupiny":"5"},
    {"value":"165","kategorie":"","label":"Teorie poznání. Epistemologie","cislo_skupiny":"5"},
    {"value":"17","kategorie":"","label":"Etika. Morální filozofie","cislo_skupiny":"5"},
    {"value":"2","kategorie":"","label":"Náboženství","cislo_skupiny":"5"},
    {"value":"2-1","kategorie":"","label":"Přirozená teologie. Náboženská filozofie","cislo_skupiny":"5"},
    {"value":"2-23/-27","kategorie":"","label":"Bible. Biblistika","cislo_skupiny":"5"},
    {"value":"2-74","kategorie":"","label":"Náboženské právo. Církevní právo","cislo_skupiny":"5"},
    {"value":"21","kategorie":"","label":"Prehistorická a primitivní náboženství","cislo_skupiny":"5"},
    {"value":"22/24","kategorie":"","label":"Náboženství Dálného východu. Indická náboženství. Hinduismus. Buddhismus","cislo_skupiny":"5"},
    {"value":"25","kategorie":"","label":"Náboženství, mytologie, kulty","cislo_skupiny":"5"},
    {"value":"26","kategorie":"","label":"Judaismus","cislo_skupiny":"5"},
    {"value":"27","kategorie":"","label":"Křesťanství. Křesťanská církev všeobecně. Eklesiologie","cislo_skupiny":"5"},
    {"value":"27-1/-2","kategorie":"","label":"Křesťanská teologie. Dogmatická teologie","cislo_skupiny":"5"},
    {"value":"27-4","kategorie":"","label":"Praktická teologie. Morální teologie","cislo_skupiny":"5"},
    {"value":"27-46/-48","kategorie":"","label":"Pastorální teologie","cislo_skupiny":"5"},
    {"value":"27-5","kategorie":"","label":"Liturgie. Křesťanské umění a symbolika. Duchovní život","cislo_skupiny":"5"},
    {"value":"27-78","kategorie":"","label":"Křesťanská sdružení, spolky a organizace. Řeholní řády","cislo_skupiny":"5"},
    {"value":"27-9","kategorie":"","label":"Dějiny křesťanské církve","cislo_skupiny":"5"},
    {"value":"271/279","kategorie":"","label":"Křesťanské církve, sekty, denominace","cislo_skupiny":"5"},
    {"value":"28","kategorie":"","label":"Islám","cislo_skupiny":"5"},
    {"value":"29","kategorie":"","label":"Moderní duchovní hnutí","cislo_skupiny":"5"},
    {"value":"3","kategorie":"","label":"Společenské vědy","cislo_skupiny":"18"},
    {"value":"304","kategorie":"","label":"Kulturní politika","cislo_skupiny":"1"},
    {"value":"308","kategorie":"","label":"Sociografie","cislo_skupiny":"18"},
    {"value":"311","kategorie":"","label":"Statistika","cislo_skupiny":"4"},
    {"value":"314","kategorie":"","label":"Demografie. Populace","cislo_skupiny":"18"},
    {"value":"316","kategorie":"","label":"Sociologie","cislo_skupiny":"18"},
    {"value":"316.3","kategorie":"","label":"Globální společnosti. Sociální struktura. Sociální skupiny","cislo_skupiny":"18"},
    {"value":"316.33","kategorie":"","label":"Ekonomická sociologie. Sociologie institucí, lidských sídel a komunit","cislo_skupiny":"18"},
    {"value":"316.36","kategorie":"","label":"Manželství a rodina. Sexuální vztahy","cislo_skupiny":"18"},
    {"value":"316.4","kategorie":"","label":"Sociální procesy","cislo_skupiny":"18"},
    {"value":"316.4/.7","kategorie":"","label":"Sociální interakce. Sociální komunikace","cislo_skupiny":"18"},
    {"value":"316.7","kategorie":"","label":"Sociologie kultury. Kulturní život","cislo_skupiny":"1"},
    {"value":"316.77","kategorie":"","label":"Informační věda","cislo_skupiny":"12"},
    {"value":"32","kategorie":"","label":"Politika","cislo_skupiny":"15"},
    {"value":"321","kategorie":"","label":"Politologie","cislo_skupiny":"15"},
    {"value":"322","kategorie":"","label":"Politika a náboženství. Vztahy mezi církví a státem","cislo_skupiny":"15"},
    {"value":"323","kategorie":"","label":"Vnitropolitický vývoj, politický život","cislo_skupiny":"15"},
    {"value":"324","kategorie":"","label":"Volby, volební kampaně, referenda","cislo_skupiny":"15"},
    {"value":"325","kategorie":"","label":"Mezinárodní migrace, exil, kolonizace","cislo_skupiny":"15"},
    {"value":"326","kategorie":"","label":"Otroctví","cislo_skupiny":"18"},
    {"value":"327","kategorie":"","label":"Mezinárodní vztahy, světová politika","cislo_skupiny":"15"},
    {"value":"328","kategorie":"","label":"Zastupitelské orgány. Vlády. Politické systémy jednotlivých zemí","cislo_skupiny":"15"},
    {"value":"329","kategorie":"","label":"Politické strany a hnutí","cislo_skupiny":"15"},
    {"value":"33","kategorie":"","label":"Ekonomie","cislo_skupiny":"4"},
    {"value":"330.5+338","kategorie":"","label":"Národní hospodářství a hospodářská politika","cislo_skupiny":"4"},
    {"value":"330.8","kategorie":"","label":"Ekonomické teorie, doktríny, směry","cislo_skupiny":"4"},
    {"value":"331","kategorie":"","label":"Práce","cislo_skupiny":"4"},
    {"value":"332","kategorie":"","label":"Regionální ekonomie, regionální ekonomika","cislo_skupiny":"4"},
    {"value":"334","kategorie":"","label":"Formy organizace a spolupráce v ekonomice","cislo_skupiny":"4"},
    {"value":"336.1/.5","kategorie":"","label":"Veřejné finance","cislo_skupiny":"4"},
    {"value":"336.7","kategorie":"","label":"Finance","cislo_skupiny":"4"},
    {"value":"338.3/.4","kategorie":"","label":"Hospodářská a výrobní odvětví","cislo_skupiny":"4"},
    {"value":"339","kategorie":"","label":"Obchod","cislo_skupiny":"4"},
    {"value":"339.3","kategorie":"","label":"Vnitřní obchod","cislo_skupiny":"4"},
    {"value":"339.5","kategorie":"","label":"Zahraniční obchod. Mezinárodní obchod","cislo_skupiny":"4"},
    {"value":"339.7/.9","kategorie":"","label":"Světová ekonomika a mezinárodní finance","cislo_skupiny":"4"},
    {"value":"34","kategorie":"","label":"Právo","cislo_skupiny":"16"},
    {"value":"341","kategorie":"","label":"Mezinárodní právo","cislo_skupiny":"16"},
    {"value":"342","kategorie":"","label":"Ústavní právo. Správní právo","cislo_skupiny":"16"},
    {"value":"342.53","kategorie":"","label":"Zákonodárství","cislo_skupiny":"16"},
    {"value":"343","kategorie":"","label":"Trestní právo","cislo_skupiny":"16"},
    {"value":"343.8","kategorie":"","label":"Vězeňství","cislo_skupiny":"18"},
    {"value":"343.9","kategorie":"","label":"Kriminalistika","cislo_skupiny":"16"},
    {"value":"343.97","kategorie":"","label":"Kriminologie","cislo_skupiny":"18"},
    {"value":"344","kategorie":"","label":"Vojenské trestní právo","cislo_skupiny":"16"},
    {"value":"346","kategorie":"","label":"Hospodářské právo","cislo_skupiny":"16"},
    {"value":"347","kategorie":"","label":"Soukromé právo","cislo_skupiny":"16"},
    {"value":"347.7","kategorie":"","label":"Obchodní právo. Finanční právo. Právo průmyslového vlastnictví. Patentové právo. Autorské právo","cislo_skupiny":"16"},
    {"value":"347.9","kategorie":"","label":"Občanské soudní řízení. Soudnictví","cislo_skupiny":"16"},
    {"value":"349","kategorie":"","label":"Pracovní, sociální, stavební právo. Právo životního prostředí","cislo_skupiny":"16"},
    {"value":"35","kategorie":"","label":"Veřejná správa","cislo_skupiny":"15"},
    {"value":"35.07","kategorie":"","label":"Organizace a řízení veřejné správy","cislo_skupiny":"15"},
    {"value":"351","kategorie":"","label":"Úkoly veřejné správy, správní opatření, legislativa","cislo_skupiny":"15"},
    {"value":"352/354","kategorie":"","label":"Stupně místní, oblastní a ústřední správy","cislo_skupiny":"15"},
    {"value":"355/359","kategorie":"","label":"Vojenství. Obrana země. Ozbrojené síly","cislo_skupiny":"15"},
    {"value":"356","kategorie":"","label":"Vojenská služba. Pěchota","cislo_skupiny":"15"},
    {"value":"357","kategorie":"","label":"Motorizované jednotky. Jezdectvo","cislo_skupiny":"15"},
    {"value":"358","kategorie":"","label":"Vojenské letectvo. Dělostřelectvo. Ženijní jednotky. Technické služby armády. Chemické vojsko","cislo_skupiny":"15"},
    {"value":"359","kategorie":"","label":"Vojenské námořnictvo a loďstvo","cislo_skupiny":"15"},
    {"value":"36","kategorie":"","label":"Zajištění duševních a materiálních potřeb","cislo_skupiny":"18"},
    {"value":"364","kategorie":"","label":"Sociální problémy vyžadující podporu a pomoc. Sociální zabezpečení","cislo_skupiny":"18"},
    {"value":"364-1/-7","kategorie":"","label":"Druhy sociální pomoci a služeb","cislo_skupiny":"18"},
    {"value":"364.3","kategorie":"","label":"Sociální pojištění. Zdravotní pojištění. Důchody","cislo_skupiny":"18"},
    {"value":"365","kategorie":"","label":"Požadavky na bydlení a jejich uspokojování","cislo_skupiny":"18"},
    {"value":"366","kategorie":"","label":"Ochrana spotřebitele. Chování spotřebitele","cislo_skupiny":"18"},
    {"value":"368","kategorie":"","label":"Pojišťovnictví","cislo_skupiny":"4"},
    {"value":"37","kategorie":"","label":"Výchova a vzdělávání","cislo_skupiny":"22"},
    {"value":"37.014","kategorie":"","label":"Vzdělávací a výchovná politika","cislo_skupiny":"22"},
    {"value":"37.016","kategorie":"","label":"Učební osnovy. Vyučovací předměty. Učebnice","cislo_skupiny":"22"},
    {"value":"37.09","kategorie":"","label":"Organizace výuky a vzdělávání","cislo_skupiny":"22"},
    {"value":"373.2/.3","kategorie":"","label":"Předškolní a primární výchova a vzdělávání","cislo_skupiny":"22"},
    {"value":"373.5","kategorie":"","label":"Střední školy","cislo_skupiny":"22"},
    {"value":"374","kategorie":"","label":"Výchova a vzdělávání dospělých. Mimoškolní výchova a vzdělávání","cislo_skupiny":"22"},
    {"value":"376","kategorie":"","label":"Výchova a vzdělávání zvláštních skupin osob","cislo_skupiny":"22"},
    {"value":"377","kategorie":"","label":"Odborné vzdělávání","cislo_skupiny":"22"},
    {"value":"378","kategorie":"","label":"Vysoké školy","cislo_skupiny":"22"},
    {"value":"39","kategorie":"","label":"Kulturní antropologie. Etnologie. Etnografie","cislo_skupiny":"1"},
    {"value":"391","kategorie":"","label":"Oděv, móda, ozdoby","cislo_skupiny":"1"},
    {"value":"392","kategorie":"","label":"Zvyky, mravy, obyčeje v soukromém životě","cislo_skupiny":"1"},
    {"value":"393","kategorie":"","label":"Smrt. Pohřby. Obyčeje při úmrtí","cislo_skupiny":"1"},
    {"value":"394","kategorie":"","label":"Veřejný a společenský život. Každodenní život","cislo_skupiny":"1"},
    {"value":"395","kategorie":"","label":"Společenské chování. Etiketa","cislo_skupiny":"1"},
    {"value":"398","kategorie":"","label":"Folklor. Lidové tradice","cislo_skupiny":"1"},
    {"value":"5","kategorie":"","label":"Přírodní vědy. Matematické vědy","cislo_skupiny":"6"},
    {"value":"502","kategorie":"","label":"Životní prostředí a jeho ochrana","cislo_skupiny":"2"},
    {"value":"504","kategorie":"","label":"Znečištění a poškození životního prostředí","cislo_skupiny":"2"},
    {"value":"51","kategorie":"","label":"Matematika","cislo_skupiny":"13"},
    {"value":"510","kategorie":"","label":"Obecné úvahy o matematice","cislo_skupiny":"13"},
    {"value":"511","kategorie":"","label":"Teorie čísel","cislo_skupiny":"13"},
    {"value":"511.1","kategorie":"","label":"Aritmetika","cislo_skupiny":"13"},
    {"value":"512","kategorie":"","label":"Algebra","cislo_skupiny":"13"},
    {"value":"514","kategorie":"","label":"Geometrie","cislo_skupiny":"13"},
    {"value":"515.1","kategorie":"","label":"Topologie","cislo_skupiny":"13"},
    {"value":"517","kategorie":"","label":"Matematická analýza","cislo_skupiny":"13"},
    {"value":"519.1/.8","kategorie":"","label":"Kombinatorika. Teorie grafů. Matematická statistika. Operační výzkum. Matematické modelování","cislo_skupiny":"13"},
    {"value":"52","kategorie":"","label":"Astronomie","cislo_skupiny":"6"},
    {"value":"520","kategorie":"","label":"Astronomické přístroje a metody","cislo_skupiny":"6"},
    {"value":"521","kategorie":"","label":"Teoretická astronomie. Nebeská mechanika","cislo_skupiny":"6"},
    {"value":"523.3","kategorie":"","label":"Země","cislo_skupiny":"6"},
    {"value":"523/524","kategorie":"","label":"Sluneční soustava. Hvězdy. Vesmír","cislo_skupiny":"6"},
    {"value":"528","kategorie":"","label":"Geodezie. Kartografie","cislo_skupiny":"7"},
    {"value":"53","kategorie":"","label":"Fyzika","cislo_skupiny":"6"},
    {"value":"531","kategorie":"","label":"Obecná mechanika. Mechanika pevných a tuhých těles","cislo_skupiny":"6"},
    {"value":"532","kategorie":"","label":"Mechanika tekutin obecně. Mechanika kapalin","cislo_skupiny":"6"},
    {"value":"533","kategorie":"","label":"Mechanika plynů. Aeromechanika. Fyzika plazmatu","cislo_skupiny":"6"},
    {"value":"534","kategorie":"","label":"Mechanické kmity. Akustika","cislo_skupiny":"6"},
    {"value":"535","kategorie":"","label":"Optika","cislo_skupiny":"6"},
    {"value":"536","kategorie":"","label":"Teplo. Termodynamika","cislo_skupiny":"6"},
    {"value":"537","kategorie":"","label":"Elektřina","cislo_skupiny":"6"},
    {"value":"537.6/.8","kategorie":"","label":"Magnetismus. Elektromagnetismus","cislo_skupiny":"6"},
    {"value":"539","kategorie":"","label":"Fyzikální stavba hmoty. Jaderná fyzika. Molekulární fyzika","cislo_skupiny":"6"},
    {"value":"54","kategorie":"","label":"Chemie. Mineralogické vědy","cislo_skupiny":"10"},
    {"value":"542","kategorie":"","label":"Praktická laboratorní chemie. Preparativní a experimentální chemie","cislo_skupiny":"10"},
    {"value":"543","kategorie":"","label":"Analytická chemie","cislo_skupiny":"10"},
    {"value":"544","kategorie":"","label":"Fyzikální chemie","cislo_skupiny":"10"},
    {"value":"546","kategorie":"","label":"Anorganická chemie","cislo_skupiny":"10"},
    {"value":"547","kategorie":"","label":"Organická chemie","cislo_skupiny":"10"},
    {"value":"548","kategorie":"","label":"Krystalografie","cislo_skupiny":"10"},
    {"value":"549","kategorie":"","label":"Mineralogie","cislo_skupiny":"7"},
    {"value":"55","kategorie":"","label":"Vědy o Zemi. Geologické vědy","cislo_skupiny":"7"},
    {"value":"550","kategorie":"","label":"Geofyzika. Geochemie. Geobiologie. Užitá geologie","cislo_skupiny":"7"},
    {"value":"551","kategorie":"","label":"Geologie. Meteorologie. Klimatologie","cislo_skupiny":"7"},
    {"value":"552","kategorie":"","label":"Petrologie","cislo_skupiny":"7"},
    {"value":"553","kategorie":"","label":"Ložisková geologie","cislo_skupiny":"7"},
    {"value":"556","kategorie":"","label":"Hydrologie","cislo_skupiny":"7"},
    {"value":"56","kategorie":"","label":"Paleontologie","cislo_skupiny":"7"},
    {"value":"57","kategorie":"","label":"Obecná biologie","cislo_skupiny":"2"},
    {"value":"57/59","kategorie":"","label":"Biologické vědy","cislo_skupiny":"2"},
    {"value":"572","kategorie":"","label":"Fyzická antropologie","cislo_skupiny":"1"},
    {"value":"574","kategorie":"","label":"Obecná ekologie","cislo_skupiny":"2"},
    {"value":"575","kategorie":"","label":"Obecná genetika. Obecná cytogenetika. Evoluce","cislo_skupiny":"2"},
    {"value":"576","kategorie":"","label":"Buněčná biologie. Cytologie","cislo_skupiny":"2"},
    {"value":"577","kategorie":"","label":"Biochemie. Molekulární biologie. Biofyzika","cislo_skupiny":"2"},
    {"value":"578","kategorie":"","label":"Virologie","cislo_skupiny":"2"},
    {"value":"579","kategorie":"","label":"Mikrobiologie","cislo_skupiny":"2"},
    {"value":"58","kategorie":"","label":"Botanika","cislo_skupiny":"2"},
    {"value":"581","kategorie":"","label":"Obecná botanika","cislo_skupiny":"2"},
    {"value":"59","kategorie":"","label":"Zoologie","cislo_skupiny":"2"},
    {"value":"591","kategorie":"","label":"Obecná zoologie","cislo_skupiny":"2"},
    {"value":"599.89","kategorie":"","label":"Hominidae. Hominidi - lidé","cislo_skupiny":"1"},
    {"value":"60","kategorie":"","label":"Biotechnologie. Genetické inženýrství","cislo_skupiny":"2"},
    {"value":"61","kategorie":"","label":"Lékařské vědy. Lékařství","cislo_skupiny":"14"},
    {"value":"611","kategorie":"","label":"Anatomie člověka a srovnávací anatomie","cislo_skupiny":"14"},
    {"value":"612","kategorie":"","label":"Fyziologie člověka a srovnávací fyziologie","cislo_skupiny":"14"},
    {"value":"613","kategorie":"","label":"Hygiena. Lidské zdraví","cislo_skupiny":"14"},
    {"value":"613.7","kategorie":"","label":"Zdraví a hygiena volného času, rekreace a spánku","cislo_skupiny":"20"},
    {"value":"614","kategorie":"","label":"Veřejné zdraví a hygiena","cislo_skupiny":"14"},
    {"value":"614.8","kategorie":"","label":"Úrazy a jejich prevence","cislo_skupiny":"14"},
    {"value":"614.84","kategorie":"","label":"Požáry. Ochrana před požáry","cislo_skupiny":"14"},
    {"value":"615","kategorie":"","label":"Farmacie. Farmakologie","cislo_skupiny":"14"},
    {"value":"615.8","kategorie":"","label":"Fyzioterapie. Psychoterapie. Alternativní lékařství","cislo_skupiny":"14"},
    {"value":"616","kategorie":"","label":"Patologie. Klinická medicína","cislo_skupiny":"14"},
    {"value":"616-053.2","kategorie":"","label":"Pediatrie","cislo_skupiny":"14"},
    {"value":"616-053.9","kategorie":"","label":"Geriatrie","cislo_skupiny":"14"},
    {"value":"616-092","kategorie":"","label":"Experimentální medicína","cislo_skupiny":"14"},
    {"value":"616.31","kategorie":"","label":"Stomatologie","cislo_skupiny":"14"},
    {"value":"616.89","kategorie":"","label":"Psychiatrie","cislo_skupiny":"14"},
    {"value":"617","kategorie":"","label":"Ortopedie. Chirurgie. Oftalmologie","cislo_skupiny":"14"},
    {"value":"618","kategorie":"","label":"Gynekologie. Porodnictví","cislo_skupiny":"14"},
    {"value":"62","kategorie":"","label":"Technika všeobecně","cislo_skupiny":"19"},
    {"value":"620.1/.2","kategorie":"","label":"Nauka o materiálu","cislo_skupiny":"19"},
    {"value":"620.9","kategorie":"","label":"Energetika","cislo_skupiny":"19"},
    {"value":"621","kategorie":"","label":"Strojírenství","cislo_skupiny":"19"},
    {"value":"621.039","kategorie":"","label":"Jaderná technika","cislo_skupiny":"19"},
    {"value":"621.3","kategorie":"","label":"Elektrotechnika","cislo_skupiny":"19"},
    {"value":"621.38","kategorie":"","label":"Elektronika","cislo_skupiny":"19"},
    {"value":"621.39","kategorie":"","label":"Sdělovací technika","cislo_skupiny":"19"},
    {"value":"622","kategorie":"","label":"Hornictví","cislo_skupiny":"19"},
    {"value":"623","kategorie":"","label":"Vojenská technika","cislo_skupiny":"19"},
    {"value":"624","kategorie":"","label":"Stavební inženýrství","cislo_skupiny":"19"},
    {"value":"625","kategorie":"","label":"Pozemní komunikace. Železniční stavitelství","cislo_skupiny":"19"},
    {"value":"626/627","kategorie":"","label":"Vodní stavitelství. Vodní hospodářství","cislo_skupiny":"19"},
    {"value":"628","kategorie":"","label":"Sanitární technika. Vodárenství. Odpadové hospodářství. Světelná technika","cislo_skupiny":"19"},
    {"value":"629","kategorie":"","label":"Dopravní prostředky","cislo_skupiny":"19"},
    {"value":"629.056.2","kategorie":"","label":"Astronomická navigace","cislo_skupiny":"19"},
    {"value":"63","kategorie":"","label":"Zemědělství a příbuzné oblasti vědy a techniky","cislo_skupiny":"24"},
    {"value":"630","kategorie":"","label":"Lesnictví","cislo_skupiny":"24"},
    {"value":"631","kategorie":"","label":"Zemědělství. Pedologie. Agrotechnika. Agroekologie","cislo_skupiny":"24"},
    {"value":"632","kategorie":"","label":"Ochrana rostlin. Fytopatologie","cislo_skupiny":"24"},
    {"value":"633","kategorie":"","label":"Rostlinná výroba","cislo_skupiny":"24"},
    {"value":"634","kategorie":"","label":"Ovocnářství","cislo_skupiny":"24"},
    {"value":"635","kategorie":"","label":"Zahrádkářství","cislo_skupiny":"24"},
    {"value":"636","kategorie":"","label":"Chov zvířat. Živočišná výroba","cislo_skupiny":"24"},
    {"value":"636.09","kategorie":"","label":"Veterinární lékařství","cislo_skupiny":"24"},
    {"value":"637","kategorie":"","label":"Živočišné produkty","cislo_skupiny":"24"},
    {"value":"638","kategorie":"","label":"Včelařství","cislo_skupiny":"24"},
    {"value":"639.1","kategorie":"","label":"Myslivost","cislo_skupiny":"24"},
    {"value":"639.2/.6","kategorie":"","label":"Rybářství","cislo_skupiny":"24"},
    {"value":"64","kategorie":"","label":"Domácí hospodářství","cislo_skupiny":"19"},
    {"value":"64-051","kategorie":"","label":"Domácí personál","cislo_skupiny":"19"},
    {"value":"640.4","kategorie":"","label":"Hotelnictví. Stravování","cislo_skupiny":"19"},
    {"value":"641","kategorie":"","label":"Kuchařství. Potraviny. Vařená jídla","cislo_skupiny":"19"},
    {"value":"642","kategorie":"","label":"Číšnictví. Servírování","cislo_skupiny":"19"},
    {"value":"643","kategorie":"","label":"Byt. Místnosti. Vybavení bytu","cislo_skupiny":"19"},
    {"value":"644","kategorie":"","label":"Bytové zařízení (sanitární)","cislo_skupiny":"19"},
    {"value":"645","kategorie":"","label":"Nábytek","cislo_skupiny":"19"},
    {"value":"646","kategorie":"","label":"Odívání. Péče o tělo","cislo_skupiny":"19"},
    {"value":"648","kategorie":"","label":"Praní. Čištění","cislo_skupiny":"19"},
    {"value":"649","kategorie":"","label":"Domácí péče o děti, nemocné a hosty","cislo_skupiny":"18"},
    {"value":"654","kategorie":"","label":"Telekomunikace a dálkové řízení","cislo_skupiny":"4"},
    {"value":"655","kategorie":"","label":"Polygrafie. Vydavatelství a knižní obchod","cislo_skupiny":"12"},
    {"value":"656","kategorie":"","label":"Doprava","cislo_skupiny":"4"},
    {"value":"656.1/.5","kategorie":"","label":"Pozemní doprava","cislo_skupiny":"4"},
    {"value":"656.2","kategorie":"","label":"Železniční doprava","cislo_skupiny":"4"},
    {"value":"656.6/.7","kategorie":"","label":"Vodní a letecká doprava","cislo_skupiny":"4"},
    {"value":"656.62","kategorie":"","label":"Říční doprava","cislo_skupiny":"4"},
    {"value":"656.8","kategorie":"","label":"Poštovní služby a správa","cislo_skupiny":"4"},
    {"value":"657","kategorie":"","label":"Účetnictví","cislo_skupiny":"4"},
    {"value":"658","kategorie":"","label":"Řízení a správa podniku","cislo_skupiny":"4"},
    {"value":"659","kategorie":"","label":"Reklama. Public relations. Média","cislo_skupiny":"4"},
    {"value":"66","kategorie":"","label":"Chemický průmysl. Chemická technologie","cislo_skupiny":"19"},
    {"value":"661","kategorie":"","label":"Chemikálie","cislo_skupiny":"19"},
    {"value":"662","kategorie":"","label":"Výbušniny. Paliva","cislo_skupiny":"19"},
    {"value":"663","kategorie":"","label":"Průmysl nápojů. Kvasný průmysl. Průmysl pochutin","cislo_skupiny":"19"},
    {"value":"664","kategorie":"","label":"Potravinářský průmysl","cislo_skupiny":"19"},
    {"value":"665","kategorie":"","label":"Oleje. Tuky. Vosky. Pojiva. Pryskyřice","cislo_skupiny":"19"},
    {"value":"666","kategorie":"","label":"Sklářství. Keramika. Cement","cislo_skupiny":"19"},
    {"value":"667","kategorie":"","label":"Průmysl barviv","cislo_skupiny":"19"},
    {"value":"669","kategorie":"","label":"Metalurgie","cislo_skupiny":"19"},
    {"value":"67/68","kategorie":"","label":"Řemesla. Různá odvětví průmyslu","cislo_skupiny":"19"},
    {"value":"671","kategorie":"","label":"Předměty z drahých kovů","cislo_skupiny":"19"},
    {"value":"672","kategorie":"","label":"Předměty ze železa a oceli","cislo_skupiny":"19"},
    {"value":"673","kategorie":"","label":"Předměty z neželezných kovů","cislo_skupiny":"19"},
    {"value":"674","kategorie":"","label":"Dřevo. Dřevařský průmysl","cislo_skupiny":"19"},
    {"value":"675","kategorie":"","label":"Kožedělný průmysl","cislo_skupiny":"19"},
    {"value":"676","kategorie":"","label":"Papírenský průmysl","cislo_skupiny":"19"},
    {"value":"677","kategorie":"","label":"Textilní průmysl","cislo_skupiny":"19"},
    {"value":"678","kategorie":"","label":"Průmysl makromolekulárních látek. Gumárenský průmysl. Průmysl plastů","cislo_skupiny":"19"},
    {"value":"679","kategorie":"","label":"Výroba kabelů, provazů a lan. Průmysl kamene","cislo_skupiny":"19"},
    {"value":"681","kategorie":"","label":"Přesná mechanika a přístroje","cislo_skupiny":"19"},
    {"value":"681.5","kategorie":"","label":"Automatizační a řídicí technika","cislo_skupiny":"19"},
    {"value":"682","kategorie":"","label":"Kovářství","cislo_skupiny":"19"},
    {"value":"683","kategorie":"","label":"Železářství. Zámečnictví. Topná zařízení","cislo_skupiny":"19"},
    {"value":"684","kategorie":"","label":"Nábytkářský průmysl","cislo_skupiny":"19"},
    {"value":"685","kategorie":"","label":"Zpracování kůže. Obuvnictví","cislo_skupiny":"19"},
    {"value":"686","kategorie":"","label":"Knihařství. Sklenářství. Kancelářské potřeby","cislo_skupiny":"19"},
    {"value":"687","kategorie":"","label":"Oděvní průmysl. Kosmetika. Kadeřnictví. Péče o vzhled","cislo_skupiny":"19"},
    {"value":"688","kategorie":"","label":"Dekorační předměty. Hračky. Galanterie","cislo_skupiny":"19"},
    {"value":"69","kategorie":"","label":"Stavebnictví","cislo_skupiny":"19"},
    {"value":"691","kategorie":"","label":"Stavební hmoty","cislo_skupiny":"19"},
    {"value":"692","kategorie":"","label":"Konstrukční prvky a části staveb","cislo_skupiny":"19"},
    {"value":"693","kategorie":"","label":"Zednické práce","cislo_skupiny":"19"},
    {"value":"694","kategorie":"","label":"Dřevěné stavby. Tesařství. Truhlářství","cislo_skupiny":"19"},
    {"value":"696","kategorie":"","label":"Instalace v budovách","cislo_skupiny":"19"},
    {"value":"697","kategorie":"","label":"Vytápění, větrání, klimatizace","cislo_skupiny":"19"},
    {"value":"698","kategorie":"","label":"Dokončovací práce","cislo_skupiny":"19"},
    {"value":"699.8","kategorie":"","label":"Ochrana budov","cislo_skupiny":"19"},
    {"value":"7.01/.09","kategorie":"","label":"Umění","cislo_skupiny":"21"},
    {"value":"71","kategorie":"","label":"Územní plánování. Urbanismus. Památková péče","cislo_skupiny":"21"},
    {"value":"712","kategorie":"","label":"Plánování krajiny. Parky. Zahrady","cislo_skupiny":"24"},
    {"value":"72","kategorie":"","label":"Architektura","cislo_skupiny":"21"},
    {"value":"72/76","kategorie":"","label":"Výtvarné umění","cislo_skupiny":"21"},
    {"value":"73","kategorie":"","label":"Sochařství, keramika, porcelán, umělecké zpracování kovů","cislo_skupiny":"21"},
    {"value":"74","kategorie":"","label":"Kresba. Umělecká řemesla","cislo_skupiny":"21"},
    {"value":"75","kategorie":"","label":"Malířství","cislo_skupiny":"21"},
    {"value":"76","kategorie":"","label":"Grafické umění. Grafika","cislo_skupiny":"21"},
    {"value":"77","kategorie":"","label":"Fotografie. Fotografické postupy","cislo_skupiny":"21"},
    {"value":"78","kategorie":"","label":"Hudba","cislo_skupiny":"9"},
    {"value":"78.01","kategorie":"","label":"Muzikologie. Dějiny hudby","cislo_skupiny":"9"},
    {"value":"78.011.26","kategorie":"","label":"Populární hudba. Populární písně. Populární taneční hudba","cislo_skupiny":"9"},
    {"value":"78.03","kategorie":"","label":"Hudební styly, vlivy, školy","cislo_skupiny":"9"},
    {"value":"78.07","kategorie":"","label":"Hudebníci, skladatelé a jiná hudební povolání","cislo_skupiny":"9"},
    {"value":"780.6","kategorie":"","label":"Hudební nástroje a příslušenství","cislo_skupiny":"9"},
    {"value":"781","kategorie":"","label":"Hudební teorie","cislo_skupiny":"9"},
    {"value":"782","kategorie":"","label":"Divadelní hudba. Opera, opereta, muzikál","cislo_skupiny":"9"},
    {"value":"783","kategorie":"","label":"Církevní hudba. Duchovní hudba. Náboženská hudba","cislo_skupiny":"9"},
    {"value":"784","kategorie":"","label":"Vokální hudba","cislo_skupiny":"9"},
    {"value":"785","kategorie":"","label":"Instrumentální hudba. Symfonická hudba. Hudba pro více nástrojů","cislo_skupiny":"9"},
    {"value":"786","kategorie":"","label":"Hudba pro klávesové nástroje","cislo_skupiny":"9"},
    {"value":"786/789","kategorie":"","label":"Hudba pro jednotlivé nástroje","cislo_skupiny":"9"},
    {"value":"787","kategorie":"","label":"Hudba pro strunné a smyčcové nástroje","cislo_skupiny":"9"},
    {"value":"788","kategorie":"","label":"Hudba pro dechové nástroje","cislo_skupiny":"9"},
    {"value":"789","kategorie":"","label":"Hudba pro bicí nástroje","cislo_skupiny":"9"},
    {"value":"79","kategorie":"","label":"Rekreace. Volný čas. Zábava. Hry. Sport","cislo_skupiny":"20"},
    {"value":"791","kategorie":"","label":"Film. Cirkus. Lidová zábava","cislo_skupiny":"3"},
    {"value":"791/793","kategorie":"","label":"Divadlo, film, tanec (obecně)","cislo_skupiny":"3"},
    {"value":"792","kategorie":"","label":"Divadlo. Divadelní představení","cislo_skupiny":"3"},
    {"value":"793","kategorie":"","label":"Společenská zábava","cislo_skupiny":"20"},
    {"value":"793.3","kategorie":"","label":"Pohybové umění. Tanec","cislo_skupiny":"3"},
    {"value":"793.8","kategorie":"","label":"Zábavná magie","cislo_skupiny":"3"},
    {"value":"794","kategorie":"","label":"Deskové a stolní hry, logické hry, hry zručnosti","cislo_skupiny":"20"},
    {"value":"794.9","kategorie":"","label":"Hry závislé na náhodě","cislo_skupiny":"20"},
    {"value":"796","kategorie":"","label":"Sport. Hry. Tělesná cvičení","cislo_skupiny":"20"},
    {"value":"797","kategorie":"","label":"Vodní sporty. Letecké sporty","cislo_skupiny":"20"},
    {"value":"798","kategorie":"","label":"Jezdectví. Sporty se zvířaty","cislo_skupiny":"20"},
    {"value":"799","kategorie":"","label":"Sportovní rybolov. Lovecký sport. Sportovní střelba","cislo_skupiny":"20"},
    {"value":"80","kategorie":"","label":"Filologie","cislo_skupiny":"11"},
    {"value":"808","kategorie":"","label":"Literární styl. Literární činnost a technika. Efektivní využívání jazyka. Spisovatelská činnost","cislo_skupiny":"11"},
    {"value":"81","kategorie":"","label":"Lingvistika. Jazyky","cislo_skupiny":"11"},
    {"value":"811.1/.8","kategorie":"","label":"Různé jazyky","cislo_skupiny":"11"},
    {"value":"811.11","kategorie":"","label":"Germánské jazyky","cislo_skupiny":"11"},
    {"value":"811.111","kategorie":"","label":"Angličtina","cislo_skupiny":"11"},
    {"value":"811.111.8","kategorie":"","label":"Jazyky pidgin a kreolské jazyky","cislo_skupiny":"11"},
    {"value":"811.112","kategorie":"","label":"Západogermánské jazyky","cislo_skupiny":"11"},
    {"value":"811.112.2","kategorie":"","label":"Němčina","cislo_skupiny":"11"},
    {"value":"811.113","kategorie":"","label":"Severogermánské jazyky","cislo_skupiny":"11"},
    {"value":"811.124","kategorie":"","label":"Latina","cislo_skupiny":"11"},
    {"value":"811.13","kategorie":"","label":"Románské jazyky","cislo_skupiny":"11"},
    {"value":"811.131","kategorie":"","label":"Italo-románské jazyky","cislo_skupiny":"11"},
    {"value":"811.133","kategorie":"","label":"Galsko-románské jazyky","cislo_skupiny":"11"},
    {"value":"811.133.1","kategorie":"","label":"Francouzština","cislo_skupiny":"11"},
    {"value":"811.134","kategorie":"","label":"Iberorománské jazyky","cislo_skupiny":"11"},
    {"value":"811.135","kategorie":"","label":"Balkánské románské jazyky","cislo_skupiny":"11"},
    {"value":"811.14","kategorie":"","label":"Řečtina","cislo_skupiny":"11"},
    {"value":"811.16","kategorie":"","label":"Slovanské jazyky","cislo_skupiny":"11"},
    {"value":"811.161","kategorie":"","label":"Východoslovanské jazyky","cislo_skupiny":"11"},
    {"value":"811.161.1","kategorie":"","label":"Ruština","cislo_skupiny":"11"},
    {"value":"811.162","kategorie":"","label":"Západoslovanské jazyky","cislo_skupiny":"11"},
    {"value":"811.162.3","kategorie":"","label":"Čeština","cislo_skupiny":"11"},
    {"value":"811.163","kategorie":"","label":"Jihoslovanské jazyky","cislo_skupiny":"11"},
    {"value":"811.17","kategorie":"","label":"Baltské jazyky","cislo_skupiny":"11"},
    {"value":"811.18","kategorie":"","label":"Albánština","cislo_skupiny":"11"},
    {"value":"811.21/.22","kategorie":"","label":"Indoíránské jazyky","cislo_skupiny":"11"},
    {"value":"811.34","kategorie":"","label":"Vymřelé jazyky neznámé klasifikace","cislo_skupiny":"11"},
    {"value":"811.35","kategorie":"","label":"Kavkazské jazyky","cislo_skupiny":"11"},
    {"value":"811.41","kategorie":"","label":"Afroasijské (hamitosemitské) jazyky","cislo_skupiny":"11"},
    {"value":"811.51","kategorie":"","label":"Uraloaltajské jazyky","cislo_skupiny":"11"},
    {"value":"811.58","kategorie":"","label":"Čínské jazyky","cislo_skupiny":"11"},
    {"value":"811.9","kategorie":"","label":"Umělé jazyky","cislo_skupiny":"11"},
    {"value":"82","kategorie":"","label":"Literatura. Literární život","cislo_skupiny":"11"},
    {"value":"82-1/-8","kategorie":"","label":"Literatura různých forem a žánrů (o ní)","cislo_skupiny":"11"},
    {"value":"82-31/-34","kategorie":"","label":"Milostná, dobrodružná, fantastická próza (o ní)","cislo_skupiny":"11"},
    {"value":"82-9","kategorie":"","label":"Literární kritika, věcná literatura a různé další žánry","cislo_skupiny":"11"},
    {"value":"82-93","kategorie":"","label":"Literatura pro děti a mládež (o ní)","cislo_skupiny":"11"},
    {"value":"82-97","kategorie":"","label":"Náboženská literatura. Duchovní literatura (o ní)","cislo_skupiny":"11"},
    {"value":"82.0","kategorie":"","label":"Literatura (teorie)","cislo_skupiny":"11"},
    {"value":"821","kategorie":"","label":"Literatura v různých jazycích","cislo_skupiny":"25"},
    {"value":"821-1/-8","kategorie":"","label":"Literatura různých forem a žánrů","cislo_skupiny":"25"},
    {"value":"821-31/-34","kategorie":"","label":"Milostná, dobrodružná, fantastická próza","cislo_skupiny":"25"},
    {"value":"821-93","kategorie":"","label":"Literatura pro děti a mládež (beletrie)","cislo_skupiny":"26"},
    {"value":"821-97","kategorie":"","label":"Náboženská literatura. Duchovní literatura","cislo_skupiny":"25"},
    {"value":"821.09","kategorie":"","label":"Literatura v různých jazycích (o ní)","cislo_skupiny":"11"},
    {"value":"821.11","kategorie":"","label":"Germánské literatury","cislo_skupiny":"25"},
    {"value":"821.11.09","kategorie":"","label":"Germánské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.111","kategorie":"","label":"Anglická literatura, anglicky psaná","cislo_skupiny":"25"},
    {"value":"821.111(73)","kategorie":"","label":"Americká literatura","cislo_skupiny":"25"},
    {"value":"821.111(73)-1","kategorie":"","label":"Americká poezie","cislo_skupiny":"25"},
    {"value":"821.111(73)-2","kategorie":"","label":"Americké drama","cislo_skupiny":"25"},
    {"value":"821.111(73)-3","kategorie":"","label":"Americká próza","cislo_skupiny":"25"},
    {"value":"821.111(73).09","kategorie":"","label":"Americká literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.111-1","kategorie":"","label":"Anglická poezie, anglicky psaná","cislo_skupiny":"25"},
    {"value":"821.111-2","kategorie":"","label":"Anglické drama, anglicky psané","cislo_skupiny":"25"},
    {"value":"821.111-3","kategorie":"","label":"Anglická próza, anglicky psaná","cislo_skupiny":"25"},
    {"value":"821.111.09","kategorie":"","label":"Anglická literatura, anglicky psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.112.2","kategorie":"","label":"Německá literatura, německy psaná","cislo_skupiny":"25"},
    {"value":"821.112.2-1","kategorie":"","label":"Německá poezie, německy psaná","cislo_skupiny":"25"},
    {"value":"821.112.2-2","kategorie":"","label":"Německé drama, německy psané","cislo_skupiny":"25"},
    {"value":"821.112.2-3","kategorie":"","label":"Německá próza, německy psaná","cislo_skupiny":"25"},
    {"value":"821.112.2.09","kategorie":"","label":"Německá literatura, německy psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.124","kategorie":"","label":"Latinská literatura, latinsky psaná","cislo_skupiny":"25"},
    {"value":"821.124-1","kategorie":"","label":"Latinská poezie, latinsky psaná","cislo_skupiny":"25"},
    {"value":"821.124-2","kategorie":"","label":"Latinské drama, latinsky psané","cislo_skupiny":"25"},
    {"value":"821.124-3","kategorie":"","label":"Latinská próza, latinsky psaná","cislo_skupiny":"25"},
    {"value":"821.124.09","kategorie":"","label":"Latinská literatura, latinsky psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.13","kategorie":"","label":"Románské literatury","cislo_skupiny":"25"},
    {"value":"821.13.09","kategorie":"","label":"Románské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.131.1","kategorie":"","label":"Italská literatura","cislo_skupiny":"25"},
    {"value":"821.131.1-1","kategorie":"","label":"Italská poezie","cislo_skupiny":"25"},
    {"value":"821.131.1-2","kategorie":"","label":"Italské drama","cislo_skupiny":"25"},
    {"value":"821.131.1-3","kategorie":"","label":"Italská próza","cislo_skupiny":"25"},
    {"value":"821.131.1.09","kategorie":"","label":"Italská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.133.1","kategorie":"","label":"Francouzská literatura, francouzsky psaná","cislo_skupiny":"25"},
    {"value":"821.133.1-1","kategorie":"","label":"Francouzská poezie, francouzsky psaná","cislo_skupiny":"25"},
    {"value":"821.133.1-2","kategorie":"","label":"Francouzské drama, francouzsky psané","cislo_skupiny":"25"},
    {"value":"821.133.1-3","kategorie":"","label":"Francouzská próza, francouzsky psaná","cislo_skupiny":"25"},
    {"value":"821.133.1.09","kategorie":"","label":"Francouzská literatura, francouzsky psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.134.2","kategorie":"","label":"Španělská literatura, španělsky psaná","cislo_skupiny":"25"},
    {"value":"821.134.2-1","kategorie":"","label":"Španělská poezie, španělsky psaná","cislo_skupiny":"25"},
    {"value":"821.134.2-2","kategorie":"","label":"Španělské drama, španělsky psané","cislo_skupiny":"25"},
    {"value":"821.134.2-3","kategorie":"","label":"Španělská próza, španělsky psaná","cislo_skupiny":"25"},
    {"value":"821.134.2.09","kategorie":"","label":"Španělská literatura, španělsky psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.134.3","kategorie":"","label":"Portugalská literatura, portugalsky psaná","cislo_skupiny":"25"},
    {"value":"821.134.3.09","kategorie":"","label":"Portugalská literatura, portugalsky psaná (o ní)","cislo_skupiny":"11"},
    {"value":"821.14","kategorie":"","label":"Řecká literatura (středověká, novodobá)","cislo_skupiny":"25"},
    {"value":"821.14'02","kategorie":"","label":"Řecká antická literatura","cislo_skupiny":"25"},
    {"value":"821.14'02-1","kategorie":"","label":"Řecká antická poezie","cislo_skupiny":"25"},
    {"value":"821.14'02-2","kategorie":"","label":"Řecké antické drama","cislo_skupiny":"25"},
    {"value":"821.14'02-3","kategorie":"","label":"Řecká antická próza","cislo_skupiny":"25"},
    {"value":"821.14'02.09","kategorie":"","label":"Řecká antická literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.14.09","kategorie":"","label":"Řecká literatura (středověká, novodobá) (o ní)","cislo_skupiny":"11"},
    {"value":"821.16","kategorie":"","label":"Slovanské literatury","cislo_skupiny":"25"},
    {"value":"821.16.09","kategorie":"","label":"Slovanské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.161","kategorie":"","label":"Východoslovanské literatury","cislo_skupiny":"25"},
    {"value":"821.161.09","kategorie":"","label":"Východoslovanské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.161.1","kategorie":"","label":"Ruská literatura","cislo_skupiny":"25"},
    {"value":"821.161.1.09","kategorie":"","label":"Ruská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.162","kategorie":"","label":"Západoslovanské literatury","cislo_skupiny":"25"},
    {"value":"821.162.09","kategorie":"","label":"Západoslovanské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.162.1","kategorie":"","label":"Polská literatura","cislo_skupiny":"25"},
    {"value":"821.162.1.09","kategorie":"","label":"Polská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.162.3","kategorie":"","label":"Česká literatura","cislo_skupiny":"25"},
    {"value":"821.162.3-1","kategorie":"","label":"Česká poezie","cislo_skupiny":"25"},
    {"value":"821.162.3-2","kategorie":"","label":"České drama","cislo_skupiny":"25"},
    {"value":"821.162.3-3","kategorie":"","label":"Česká próza","cislo_skupiny":"25"},
    {"value":"821.162.3.09","kategorie":"","label":"Česká literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.162.4","kategorie":"","label":"Slovenská literatura","cislo_skupiny":"25"},
    {"value":"821.162.4.09","kategorie":"","label":"Slovenská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.163","kategorie":"","label":"Jihoslovanské literatury","cislo_skupiny":"25"},
    {"value":"821.163.09","kategorie":"","label":"Jihoslovanské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.163.1","kategorie":"","label":"Staroslověnská literatura","cislo_skupiny":"25"},
    {"value":"821.163.1.09","kategorie":"","label":"Staroslověnská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.17","kategorie":"","label":"Baltské literatury","cislo_skupiny":"25"},
    {"value":"821.17.09","kategorie":"","label":"Baltské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.41","kategorie":"","label":"Afroasijské (hamitosemitské) literatury","cislo_skupiny":"25"},
    {"value":"821.41.09","kategorie":"","label":"Afroasijské (hamitosemitské) literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.432","kategorie":"","label":"Nigerokonžské literatury","cislo_skupiny":"25"},
    {"value":"821.432.09","kategorie":"","label":"Nigerokonžské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.51","kategorie":"","label":"Uraloaltajské literatury","cislo_skupiny":"25"},
    {"value":"821.51.09","kategorie":"","label":"Uraloaltajské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.521","kategorie":"","label":"Japonská literatura","cislo_skupiny":"25"},
    {"value":"821.521.09","kategorie":"","label":"Japonská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.531","kategorie":"","label":"Korejská literatura","cislo_skupiny":"25"},
    {"value":"821.531.09","kategorie":"","label":"Korejská literatura (o ní)","cislo_skupiny":"11"},
    {"value":"821.58","kategorie":"","label":"Sino-tibetské literatury","cislo_skupiny":"25"},
    {"value":"821.58.09","kategorie":"","label":"Sino-tibetské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.62","kategorie":"","label":"Austronéské literatury","cislo_skupiny":"25"},
    {"value":"821.62.09","kategorie":"","label":"Austronéské literatury (o nich)","cislo_skupiny":"11"},
    {"value":"821.81/.82","kategorie":"","label":"Literatury severoamerických Indiánů","cislo_skupiny":"25"},
    {"value":"821.81/.82.09","kategorie":"","label":"Literatury severoamerických Indiánů (o nich)","cislo_skupiny":"11"},
    {"value":"821.873","kategorie":"","label":"Literatury andsko-rovníkových jazyků","cislo_skupiny":"25"},
    {"value":"821.873.09","kategorie":"","label":"Literatury andsko-rovníkových jazyků (o nich)","cislo_skupiny":"11"},
    {"value":"82:03","kategorie":"","label":"Literární slovníky, encyklopedie. Konkordance","cislo_skupiny":"11"},
    {"value":"82:05","kategorie":"","label":"Literární revue, časopisy","cislo_skupiny":"11"},
    {"value":"82:06","kategorie":"","label":"Literární organizace, soutěže","cislo_skupiny":"11"},
    {"value":"82:37","kategorie":"","label":"Literární výchovné programy","cislo_skupiny":"11"},
    {"value":"9","kategorie":"","label":"Geografie. Biografické studie. Dějiny","cislo_skupiny":"8"},
    {"value":"902","kategorie":"","label":"Archeologie","cislo_skupiny":"8"},
    {"value":"903","kategorie":"","label":"Pravěk","cislo_skupiny":"8"},
    {"value":"904","kategorie":"","label":"Kulturní památky historického období obecně","cislo_skupiny":"8"},
    {"value":"908","kategorie":"","label":"Studium oblastí a lokalit obecně","cislo_skupiny":"8"},
    {"value":"908(437)","kategorie":"","label":"Vlastivěda Česka a Slovenska","cislo_skupiny":"8"},
    {"value":"91","kategorie":"","label":"Geografie jako věda. Výzkum. Cestování","cislo_skupiny":"7"},
    {"value":"911","kategorie":"","label":"Obecná geografie. Systematická geografie","cislo_skupiny":"7"},
    {"value":"912","kategorie":"","label":"Mapy. Atlasy. Glóby","cislo_skupiny":"7"},
    {"value":"912:51","kategorie":"","label":"Matematická geografie","cislo_skupiny":"7"},
    {"value":"912:904","kategorie":"","label":"Staré mapy","cislo_skupiny":"7"},
    {"value":"913","kategorie":"","label":"Regionální geografie","cislo_skupiny":"7"},
    {"value":"913(3)","kategorie":"","label":"Geografie starověkého světa","cislo_skupiny":"7"},
    {"value":"913(4)","kategorie":"","label":"Geografie Evropy, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(437)","kategorie":"","label":"Geografie Česka a Slovenska, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(5)","kategorie":"","label":"Geografie Asie, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(6)","kategorie":"","label":"Geografie Afriky, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(7)","kategorie":"","label":"Geografie Severní Ameriky, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(8)","kategorie":"","label":"Geografie Jižní Ameriky, reálie, cestování","cislo_skupiny":"7"},
    {"value":"913(9)","kategorie":"","label":"Geografie Oceánie, polárních oblastí, Austrálie, atd.","cislo_skupiny":"7"},
    {"value":"913:94","kategorie":"","label":"Historická geografie","cislo_skupiny":"7"},
    {"value":"929","kategorie":"","label":"Biografie","cislo_skupiny":"8"},
    {"value":"929.5/.9","kategorie":"","label":"Genealogie. Heraldika. Šlechta. Vlajky","cislo_skupiny":"8"},
    {"value":"93/94","kategorie":"","label":"Dějiny (obecně)","cislo_skupiny":"8"},
    {"value":"930","kategorie":"","label":"Historická věda. Pomocné vědy historické. Archivnictví","cislo_skupiny":"8"},
    {"value":"930.85","kategorie":"","label":"Dějiny civilizace. Kulturní dějiny","cislo_skupiny":"8"},
    {"value":"94(100)\"04/...\"","kategorie":"","label":"Dějiny středověku a novověku (obecně)","cislo_skupiny":"8"},
    {"value":"94(100)","kategorie":"","label":"Světové dějiny","cislo_skupiny":"8"},
    {"value":"94(3)","kategorie":"","label":"Dějiny zemí starověkého světa","cislo_skupiny":"8"},
    {"value":"94(4)","kategorie":"","label":"Dějiny Evropy","cislo_skupiny":"8"},
    {"value":"94(41)","kategorie":"","label":"Dějiny britských ostrovů","cislo_skupiny":"8"},
    {"value":"94(420/429)","kategorie":"","label":"Dějiny Anglie a Walesu","cislo_skupiny":"8"},
    {"value":"94(430/439)","kategorie":"","label":"Dějiny zemí střední Evropy","cislo_skupiny":"8"},
    {"value":"94(437)","kategorie":"","label":"Dějiny Česka a Slovenska","cislo_skupiny":"8"},
    {"value":"94(44/449.49)","kategorie":"","label":"Dějiny Francie a Monaka","cislo_skupiny":"8"},
    {"value":"94(450/458.2)","kategorie":"","label":"Dějiny Itálie a italských ostrovů, San Marina, Vatikánu a Malty","cislo_skupiny":"8"},
    {"value":"94(46)","kategorie":"","label":"Dějiny států a území na Pyrenejském poloostrově","cislo_skupiny":"8"},
    {"value":"94(47)","kategorie":"","label":"Dějiny zemí východní Evropy","cislo_skupiny":"8"},
    {"value":"94(47+57)","kategorie":"","label":"Dějiny SSSR a Ruska","cislo_skupiny":"8"},
    {"value":"94(48)","kategorie":"","label":"Dějiny skandinávských zemí","cislo_skupiny":"8"},
    {"value":"94(491.1/494.9)","kategorie":"","label":"Dějiny ostatních evropských států","cislo_skupiny":"8"},
    {"value":"94(495/498)","kategorie":"","label":"Dějiny států a území na Balkánském poloostrově","cislo_skupiny":"8"},
    {"value":"94(5)","kategorie":"","label":"Dějiny Asie. Orient","cislo_skupiny":"8"},
    {"value":"94(510/519)","kategorie":"","label":"Dějiny Číny, Mongolska a Koreje","cislo_skupiny":"8"},
    {"value":"94(520)","kategorie":"","label":"Dějiny Japonska","cislo_skupiny":"8"},
    {"value":"94(53)","kategorie":"","label":"Dějiny států a území na Arabském poloostrově","cislo_skupiny":"8"},
    {"value":"94(54)","kategorie":"","label":"Dějiny států indického subkontinentu","cislo_skupiny":"8"},
    {"value":"94(55)","kategorie":"","label":"Dějiny Íránu","cislo_skupiny":"8"},
    {"value":"94(560/569.5)","kategorie":"","label":"Dějiny států západní Asie. Blízký východ","cislo_skupiny":"8"},
    {"value":"94(574/575.4)","kategorie":"","label":"Dějiny států Střední Asie","cislo_skupiny":"8"},
    {"value":"94(581)","kategorie":"","label":"Dějiny Afghánistánu","cislo_skupiny":"8"},
    {"value":"94(59)","kategorie":"","label":"Dějiny států jihovýchodní Asie","cislo_skupiny":"8"},
    {"value":"94(6)","kategorie":"","label":"Dějiny Afriky","cislo_skupiny":"8"},
    {"value":"94(61)","kategorie":"","label":"Dějiny Tunisu a Libye","cislo_skupiny":"8"},
    {"value":"94(62)","kategorie":"","label":"Dějiny Egypta a Súdánu","cislo_skupiny":"8"},
    {"value":"94(63)","kategorie":"","label":"Dějiny Etiopie a Eritreje","cislo_skupiny":"8"},
    {"value":"94(64)","kategorie":"","label":"Dějiny států a území severozápadní Afriky a přilehlých ostrovů","cislo_skupiny":"8"},
    {"value":"94(65)","kategorie":"","label":"Dějiny Alžírska","cislo_skupiny":"8"},
    {"value":"94(66/67)","kategorie":"","label":"Dějiny Afriky na jih od Sahary a států/území západní Afriky a přilehlých ostrovů","cislo_skupiny":"8"},
    {"value":"94(671/679)","kategorie":"","label":"Dějiny států a území střední Afriky a přilehlých ostrovů. Rovníková Afrika","cislo_skupiny":"8"},
    {"value":"94(680/689.7)","kategorie":"","label":"Dějiny států a území jižní Afriky","cislo_skupiny":"8"},
    {"value":"94(69)","kategorie":"","label":"Dějiny afrických ostrovů v Indickém a jižním Atlantském oceánu","cislo_skupiny":"8"},
    {"value":"94(7)","kategorie":"","label":"Dějiny Severní a Střední Ameriky","cislo_skupiny":"8"},
    {"value":"94(71)","kategorie":"","label":"Dějiny Kanady","cislo_skupiny":"8"},
    {"value":"94(72)","kategorie":"","label":"Dějiny Střední Ameriky a Karibské oblasti","cislo_skupiny":"8"},
    {"value":"94(73)","kategorie":"","label":"Dějiny Spojených států amerických","cislo_skupiny":"8"},
    {"value":"94(734)","kategorie":"","label":"Dějiny severovýchodních států USA","cislo_skupiny":"8"},
    {"value":"94(735)","kategorie":"","label":"Dějiny jihovýchodních států USA","cislo_skupiny":"8"},
    {"value":"94(736)","kategorie":"","label":"Dějiny států jižní části středních USA","cislo_skupiny":"8"},
    {"value":"94(737)","kategorie":"","label":"Dějiny států severní části středních USA","cislo_skupiny":"8"},
    {"value":"94(738)","kategorie":"","label":"Dějiny západních států USA","cislo_skupiny":"8"},
    {"value":"94(739)","kategorie":"","label":"Dějiny států na tichomořském pobřeží USA","cislo_skupiny":"8"},
    {"value":"94(8)","kategorie":"","label":"Dějiny Jižní Ameriky. Latinská Amerika","cislo_skupiny":"8"},
    {"value":"94(81)","kategorie":"","label":"Dějiny Brazílie","cislo_skupiny":"8"},
    {"value":"94(82)","kategorie":"","label":"Dějiny Argentiny","cislo_skupiny":"8"},
    {"value":"94(83)","kategorie":"","label":"Dějiny Chile","cislo_skupiny":"8"},
    {"value":"94(84)","kategorie":"","label":"Dějiny Bolívie","cislo_skupiny":"8"},
    {"value":"94(85)","kategorie":"","label":"Dějiny Peru","cislo_skupiny":"8"},
    {"value":"94(861/866)","kategorie":"","label":"Dějiny Kolumbie a Ekvádoru","cislo_skupiny":"8"},
    {"value":"94(87)","kategorie":"","label":"Dějiny Venezuely","cislo_skupiny":"8"},
    {"value":"94(88)","kategorie":"","label":"Dějiny Guayany a Surinamu","cislo_skupiny":"8"},
    {"value":"94(892/899)","kategorie":"","label":"Dějiny Paraguaye a Uruguaye","cislo_skupiny":"8"},
    {"value":"94(9)","kategorie":"","label":"Dějiny Oceánie, Austrálie, Arktidy a Antarktidy","cislo_skupiny":"8"},
    {"value":"94(931)","kategorie":"","label":"Dějiny Nového Zélandu","cislo_skupiny":"8"},
    {"value":"94(932/935)","kategorie":"","label":"Dějiny států a oblastí Melanésie","cislo_skupiny":"8"},
    {"value":"94(94)","kategorie":"","label":"Dějiny Austrálie","cislo_skupiny":"8"},
    {"value":"94(954)","kategorie":"","label":"Dějiny Papuy-Nové Guiney","cislo_skupiny":"8"},
    {"value":"94(961/968)","kategorie":"","label":"Dějiny států a oblastí Polynésie a Mikronésie","cislo_skupiny":"8"},
    {"value":"94(97)","kategorie":"","label":"Ostrovy Tichého oceánu","cislo_skupiny":"8"},
    {"value":"94(98/99)","kategorie":"","label":"Dějiny území Arktidy a Antarktidy","cislo_skupiny":"8"}
];

function generate_konspekt() {
    $("input[id^='tag_072_subfield_a']").each(function () {
        $(this).autocomplete({
            minLength: 0,
            source: konspekt,
            select: function (e, i) {
                parentDiv = $(this).parents("div[id^='tag_']");
                parentDiv.find("input[id*='subfield_x']").val(label = i["item"]["label"]);
                parentDiv.find("input[id*='subfield_2']").val(label = "Konspekt");
                parentDiv.find("input[id*='subfield_9']").val(label = i["item"]["cislo_skupiny"]);
            }
        });
        $(this).focus(function () {
            $(this).autocomplete("search","");
        });
        $(this).css("background-color","#FFFF44");
    });
}

generate_konspekt();
$(".buttonPlus").click(generate_konspekt);

