<!-- Modal -->
<div id="card_payment_dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="cardPaymentModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="cardPaymentModalLabel">Card payment</h4>
      </div>
      <div class="modal-body">
        <p class="transaction-message"></p>
      </div>
      <div class="modal-footer">
        <button id="transaction-close" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
