<script type="text/javascript">
    //<![CDATA[
        var MSG_POS_IN_PROGRESS = _("Transaction is in progress...");
        var MSG_POS_SUCESS = _("Transaction successfully finished, thank you.");
        var MSG_POS_INIT = _("Initializing connection...");
        var MSG_POS_REQUEST_PAYMENT = _("Requesting payment transaction...");
        var MSG_POS_REQUEST_REFUND = _("Requesting refund transaction...");
        var MSG_POS_SENT_REQUEST = _("Request sent.");
        var MSG_POS_RECEIVED_MESSAGE = _("Request confirmed.");
        var MSG_POS_RECEIVED_RESPONSE = _("Response received.");
        var MSG_POS_SENT_CONFIRMATION = _("Transaction confirmed.");
        var MSG_POS_DISCONNECTED = _("Device disconnected.");
        var MSG_POS_ERR_TRANSACTION_REJECTED = _("Transaction rejected.");
        var MSG_POS_ERR_REQUEST_REJECTED = _("Connection request rejected.");
        var MSG_POS_ERR_CONNECTION_FAILED = _("Conection interrupted.");
        var MSG_POS_ERR = _("Error:");
        var MSG_POS_ERR_CONNECTION_ABORTED = _("Connection aborted.");
        var MSG_POS_ERR_EXPIRED = _("Session timed out. Please log in again.");
        var MSG_POS_ACTIVITY_MESSAGE = _("Activity message received.");
    //]]>
</script>
